### ISSUE TITLE
Chrome breaking after installation

### ISSUE THREAD

**Issue by jessleenyc** [weerd/dotfiles#5]
Hi @weerd! 

After I went through the installation process, I started encountering the below error with 75% of websites I visit on Chrome. 

I followed all of Chromes instructions to fix it -- upgrade chrome, disable/remove all extensions, clear cache, reset chrome, etc. Nothing worked. 

All sites working fine on Safari. Let me know if you have any idea what might have caused this. I also checked the console but not seeing any errors. 

<img width="1266" alt="screen shot 2017-01-08 at 8 17 49 pm" src="https://cloud.githubusercontent.com/assets/14931921/21755286/875afab2-d5df-11e6-9f1e-7f17e29cebcd.png">

**Comment by weerd** [comment]
Hmmm, @jessleenyc yeah this is weird. Not sure what would have caused this, but if it happened after running the scripts than it likely did something. If your computer was already setup prior to running it, it may have conflicted with something. The ideal time to run the repo from the **install.sh** script is on a new computer, or newly wiped computer. Otherwise you probably want to run scripts as needed (for example to setup Sublime separately). 

Good news is, I believe everything is reverse-able :) We can take a look IRL and figure it out!

I updated the README to add a new section up top on **Usage** to better describe the scenarios for use: https://github.com/weerd/dotfiles#usage

**Comment by jessleenyc** [comment]
@weerd, discovered the version of chrome you had downloaded works fine..so I deleted my previous version. All is well again. Too bad I'm a safari user now.

**Comment by weerd** [comment]
Hmm, it might have just been mad that there were 2 versions installed. :shrug: Glad to hear it worked out though!
